### ISSUE TITLE
`yarn outdated` fails but `yarn` works!

### ISSUE THREAD

**Issue by kfiroo** [expo/react-native-action-sheet#24]
Hey guys,
This is probably not an issue with this project, but thought you might want to know, and maybe encoutered it before,
So, running `yarn` in my react-native project worked well.
However, running `yarn outdated` fails with this error

```
Trace:
  Error: https://registry.yarnpkg.com/@exponent/react-native-action-sheet: Not found
      at Request.params.callback [as _callback] (/.nvm/versions/node/v4.5.0/lib/node_modules/yarn/lib-legacy/util/request-manager.js:306:18)
      at Request.self.callback (/.nvm/versions/node/v4.5.0/lib/node_modules/yarn/node_modules/request/request.js:186:22)
      at emitTwo (events.js:87:13)
      at Request.emit (events.js:172:7)
      at Request.<anonymous> (/.nvm/versions/node/v4.5.0/lib/node_modules/yarn/node_modules/request/request.js:1081:10)
      at emitOne (events.js:77:13)
      at Request.emit (events.js:169:7)
      at IncomingMessage.<anonymous> (/.nvm/versions/node/v4.5.0/lib/node_modules/yarn/node_modules/request/request.js:1001:12)
      at IncomingMessage.g (events.js:260:16)
      at emitNone (events.js:72:20)
```

**Comment by peterpme** [comment]
Hey thanks!

Perhaps this major release (1.0.2) will be able to help:
https://www.npmjs.com/package/@expo/react-native-action-sheet
